### ISSUE TITLE
Meeting Mai 2015

### ISSUE THREAD

**Issue by halfbyte** [rughh/planning#11] opened 2015-04-08 18:16 UTC
* [x] Location
* [x] [Talks / Format](https://github.com/rughh/planning/wiki/Speaker-Checklist)
* [x] Promo auf Twitter
* [x] [Push-Notification für iOS app senden](http://hamburg.onruby.de/admin/dashboard)
* [x] [Slides anpassen](https://docs.google.com/presentation/d/1qbNdAffMiYkPWUrUd5xeWHq6ge6vhIVQtuZomdiSorU/edit?usp=sharing)

**Comment by phoet** [comment] 2015-04-09 08:16
assigned to jan because of shortest stöckchen

**Comment by phoet** [comment] 2015-04-22 07:07
just because we might be a little busy preparing our sweden trip to @weidenfreak, maybe we want to delegate the organization of this event to @codestars at jimdo in case he is interested?

**Comment by phoet** [comment] 2015-04-22 07:08
meh, i meant @nesQuick

**Comment by nesQuick** [comment] 2015-04-22 08:56
Yeah, sure. Happy to take it over. But would appriciate any good pointers for speakers :microphone: Location will be Jimdo, because it's easy :wink:

**Comment by titanoboa** [comment] 2015-04-22 12:00
@nesQuick http://hamburg.onruby.de/#topics currently has two talks offered

**Comment by phoet** [comment] 2015-04-22 12:15
i don't know if @skorfmann is back in hamburg yet

**Comment by titanoboa** [comment] 2015-04-22 12:49
he is sitting next door, more or less

**Comment by titanoboa** [comment] 2015-04-22 12:50
ah, @ mention, so he can answer himself
(ich sollte lernen dieses neumodische internetzeugs zu bedienen)

**Comment by skorfmann** [comment] 2015-04-22 13:07
> i don't know if @skorfmann is back in hamburg yet

Yes, I am in Hamburg :) - but I'll be away from 8. - 23. of May. However, June would work.

**Comment by nesQuick** [comment] 2015-04-29 20:08
Well just figured they are both from @skorfmann I will see, if I will find any cool talks. Any thoughts about mixing one remote talk in?

**Comment by alto** [comment] 2015-04-30 05:55
I would like to invite people to work in New Zealand (and introduce [Abletech](https://abletech.nz)). Remote via Skype or so. 10 minutes, after 21:00 Hamburg time (7 a.m. New Zealand).

**Comment by nesQuick** [comment] 2015-04-30 17:48
@alto sounds good. I just checked with our office staff and we will have everything one might need (esp. speakers) so could your add your talk here http://hamburg.onruby.de/topics/new *please*

One (or two) talks slots left :)

**Comment by alto** [comment] 2015-05-01 00:13
Hmm, Carl from Abletech is not available this month (and I would like to do it together with him). Let's postpone it until later.

Cheers,
Thorsten

**Comment by phoet** [comment] 2015-05-08 18:46
@nesQuick topic -> http://hamburg.onruby.de/topics/byol-bring-your-own-logging

do you want to fiddle with the admin-backend to setup the event and do a little promotion on the interwebs? you should have twitter access as well, the credentials are [here](https://github.com/rughh/logins)

**Comment by nesQuick** [comment] 2015-05-11 09:05
ja!

**Comment by nesQuick** [comment] 2015-05-11 09:22
Ahh, took me a while to realize I had to create the event at onruby, I could have done this way before, sorry :D We are almost done with the programm, @phoet does one talk and I try to find some other talk as well :)

**Comment by nesQuick** [comment] 2015-05-11 09:22
Also toot'd :bird:

**Comment by nesQuick** [comment] 2015-05-11 15:23
Two talk confirmed, better late then never :dancer:

**Comment by titanoboa** [comment] 2015-05-11 20:31
:+1: 

btw I sadly won't make it on Wedenesday

**Closed** 2015-05-24 20:17 UTC
